version: "1"
rules:
  - base: master
    upstream: fedarovich:master    # change `wei` to the owner of upstream repo
    mergeMethod: merge
    mergeUnstable: false
    conflictReviewers:
      - azhuge233
