name: Publish

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/**.md'
      - '.github/**'

jobs:
  publish:
    name: Publish the app
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Publish
      shell: pwsh
      run: |
        Set-Location "$env:GITHUB_WORKSPACE\src\QBittorrent.CommandLineInterface"
        dotnet restore
        dotnet publish -f net6 -c release -r linux-x64 -o "Release\linux-x64" -p:PublishSingleFile=true -p:PublishTimmed=true -p:DebugType=None -p:DebugSymbols=false --sc
        dotnet publish -f net6 -c release -r win-x64 -o "Release\win-x64" -p:PublishSingleFile=true -p:PublishTimmed=true -p:DebugType=None -p:DebugSymbols=false --sc
        dotnet publish -f net6 -c release -r osx-x64 -o "Release\osx-x64" -p:PublishSingleFile=true -p:PublishTimmed=true -p:DebugType=None -p:DebugSymbols=false --sc
        Compress-Archive -Path "Release\win-x64\" -DestinationPath "qbt-win-x64.zip"
        Compress-Archive -Path "Release\linux-x64\" -DestinationPath "qbt-linux-x64.zip"
        Compress-Archive -Path "Release\osx-x64\" -DestinationPath "qbt-osx-x64.zip"
        
    - name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        files: ./src/QBittorrent.CommandLineInterface/*.zip
